# This is a basic workflow to help you get started with Actions

name: Build Executables

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.3'
          channel: 'stable'

      - name: Enable required platforms
        working-directory: ./pslab_flutter_demo
        run: |
             flutter config --enable-macos-desktop
             flutter config --enable-ios
             flutter config --no-enable-linux-desktop
             flutter config --no-enable-windows-desktop
             flutter config --no-enable-android

      - name: Checking
        working-directory: ./pslab_flutter_demo
        run: flutter doctor

      - name: Get dependencies
        working-directory: ./pslab_flutter_demo
        run: flutter pub get

      - name: Build ios
        working-directory: ./pslab_flutter_demo
        run: flutter build ios --release --no-codesign

      - name: Build macos
        working-directory: ./pslab_flutter_demo
        run: flutter build macos

      - uses: actions/upload-artifact@v2
        with:
          name: executables
          path: |
            ./pslab_flutter_demo/build/ios/iphoneos/Runner.app
            ./pslab_flutter_demo/build/app/outputs/apk/release/app-release.apk
